-- MySQL Script generated by MySQL Workbench
-- 06/03/19 17:57:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bucho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bucho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bucho` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bucho` ;

-- -----------------------------------------------------
-- Table `bucho`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bucho`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(60) NOT NULL COMMENT '',
  `email` VARCHAR(80) NOT NULL COMMENT '',
  `senha` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`idCliente`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bucho`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bucho`.`Mesa` (
  `idMesa` INT NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`idMesa`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bucho`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bucho`.`Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `data` DATE NOT NULL COMMENT '',
  `hora` TIME(4) NOT NULL COMMENT '',
  `numCadeira` INT(4) NOT NULL COMMENT '',
  `Cliente_idCliente` INT NOT NULL COMMENT '',
  `Mesa_idMesa` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idReserva`)  COMMENT '',
  INDEX `fk_Reserva_Cliente1_idx` (`Cliente_idCliente` ASC)  COMMENT '',
  INDEX `fk_Reserva_Mesa1_idx` (`Mesa_idMesa` ASC)  COMMENT '',
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `bucho`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Mesa1`
    FOREIGN KEY (`Mesa_idMesa`)
    REFERENCES `bucho`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bucho`.`FotoComida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bucho`.`FotoComida` (
  `idFoto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `endereco` VARCHAR(300) NOT NULL COMMENT '',
  PRIMARY KEY (`idFoto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bucho`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bucho`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(20) NOT NULL COMMENT '',
  `senha` VARCHAR(20) NOT NULL COMMENT '',
  `email` VARCHAR(80) NOT NULL COMMENT '',
  PRIMARY KEY (`idFuncionario`)  COMMENT '',
  UNIQUE INDEX `login_UNIQUE` (`login` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bucho`.`Prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bucho`.`Prato` (
  `idPrato` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(60) NOT NULL COMMENT '',
  `categoria` VARCHAR(20) NOT NULL COMMENT '',
  `descricao` VARCHAR(500) NOT NULL COMMENT '',
  `preco` FLOAT(5) NOT NULL COMMENT '',
  `Imagem_idFoto` INT NOT NULL COMMENT '',
  `Funcionario_idFuncionario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPrato`)  COMMENT '',
  INDEX `fk_Prato_Imagem1_idx` (`Imagem_idFoto` ASC)  COMMENT '',
  INDEX `fk_Prato_Funcionario1_idx` (`Funcionario_idFuncionario` ASC)  COMMENT '',
  CONSTRAINT `fk_Prato_Imagem1`
    FOREIGN KEY (`Imagem_idFoto`)
    REFERENCES `bucho`.`FotoComida` (`idFoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prato_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `bucho`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bucho`.`FotoEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bucho`.`FotoEvento` (
  `idFoto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `endereco` VARCHAR(300) NOT NULL COMMENT '',
  PRIMARY KEY (`idFoto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bucho`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bucho`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(60) NOT NULL COMMENT '',
  `data` DATE NOT NULL COMMENT '',
  `hora` TIME(4) NOT NULL COMMENT '',
  `descricao` VARCHAR(500) NOT NULL COMMENT '',
  `Funcionario_idFuncionario` INT NOT NULL COMMENT '',
  `FotoEvento_idFoto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idEvento`)  COMMENT '',
  INDEX `fk_Evento_Funcionario1_idx` (`Funcionario_idFuncionario` ASC)  COMMENT '',
  INDEX `fk_Evento_FotoEvento1_idx` (`FotoEvento_idFoto` ASC)  COMMENT '',
  CONSTRAINT `fk_Evento_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `bucho`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_FotoEvento1`
    FOREIGN KEY (`FotoEvento_idFoto`)
    REFERENCES `bucho`.`FotoEvento` (`idFoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO funcionario VALUES (0, 'admin', 'admin', 'buchodebode@gmail.com');
UPDATE funcionario SET idFuncionario= 1,  login='admin', senha='admin', email='buchodebode@gmail.com' where login='admin';